/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indrajeet
 */
public class ApplicationApply extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationApply
     */
    String aouserEmail="";
    String appliedvid="";
    public ApplicationApply() {
        initComponents();
        appliedpanel.setVisible(false);
        availablepanel.setVisible(false);
        status.setVisible(false);
        statuscross.setVisible(false);
        statusLabel.setVisible(false);
        clickLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        clickLabel = new javax.swing.JLabel();
        statuscross = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        appliedpanel = new javax.swing.JScrollPane();
        appliedtable = new javax.swing.JTable();
        availablepanel = new javax.swing.JScrollPane();
        availabletable = new javax.swing.JTable();
        appliedbtn = new javax.swing.JButton();
        availablebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 500, 50));

        clickLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clickLabel.setText("Click Respective Row to Apply . . .");
        getContentPane().add(clickLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        statuscross.setBackground(new java.awt.Color(242, 242, 242));
        statuscross.setForeground(new java.awt.Color(242, 242, 242));
        statuscross.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\Close.png")); // NOI18N
        statuscross.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statuscross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statuscrossActionPerformed(evt);
            }
        });
        getContentPane().add(statuscross, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, 40, 40));

        status.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 680, 270));

        appliedtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volunteer Id", "Title", "Volunteers Required", "Applied", "Selected"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appliedtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appliedtableMouseClicked(evt);
            }
        });
        appliedtable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                appliedtableComponentShown(evt);
            }
        });
        appliedpanel.setViewportView(appliedtable);

        getContentPane().add(appliedpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 1040, 430));

        availabletable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Title", "Students Required", "Volunteering Period (in days)", "Last Date to Apply", "Contact Email", "More Details"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        availabletable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availabletableMouseClicked(evt);
            }
        });
        availabletable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                availabletableComponentShown(evt);
            }
        });
        availablepanel.setViewportView(availabletable);

        getContentPane().add(availablepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 1040, 430));

        appliedbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        appliedbtn.setText("APPLIED ACTIVITIES");
        appliedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appliedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(appliedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 350, 50));

        availablebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        availablebtn.setText("ACTIVITIES POSTED BY ORGANISER");
        availablebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablebtnActionPerformed(evt);
            }
        });
        getContentPane().add(availablebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 350, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 1100, 510));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\48\\05 - Arrow Left.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        logoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\exit.png")); // NOI18N
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\admin dahsboard.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserDashboard ud=new UserDashboard();
        ud.setVisible(true);
        ud.userEmail=aouserEmail;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        UserLogin l=new UserLogin();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void availablebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablebtnActionPerformed
        // TODO add your handling code here:
        
        availablebtn.setBackground(Color.BLUE);
        appliedbtn.setBackground(Color.white);
        appliedpanel.setVisible(false);
        availablepanel.setVisible(true);
        clickLabel.setVisible(true);                                
        // TODO add your handling code here:

        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select code, title, studentrequired, period, lastdate, contactemail, moredetails from opportunities where lastdate >= NOW()");
            //            st.setString(1, usernameData);
            ResultSet rs=st.executeQuery();
            PreparedStatement st1=(PreparedStatement)
            conn.prepareStatement("select code, title, studentrequired, period, lastdate, contactemail, moredetails from opportunities where lastdate >= NOW()");
            ResultSet rs1=st1.executeQuery();
            if(rs1.next()==false)
            {
                appliedbtn.setEnabled(true);
                availablebtn.setEnabled(false);
                JOptionPane.showMessageDialog(this, "No Volunteering Opportunities Available! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while(rs.next())
            {
                String code=rs.getString("code");
                String title=rs.getString("title");
                String stduentsrequired=rs.getString("studentrequired");
                String period=rs.getString("period");
                String lastdate=rs.getString("lastdate");
                String contactemail=rs.getString("contactemail");
                String moredetails=rs.getString("moredetails");

                String tableData[]={code, title, stduentsrequired, period, lastdate, contactemail, moredetails};
                DefaultTableModel tableModel=(DefaultTableModel) availabletable.getModel();
                tableModel.addRow(tableData);
                availablebtn.setEnabled(false);
                
                appliedbtn.setEnabled(true);
            }

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
        }
        DefaultTableModel tableModel=(DefaultTableModel) appliedtable.getModel();
        tableModel.setRowCount(0);
        
        
    }//GEN-LAST:event_availablebtnActionPerformed

    private void appliedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appliedbtnActionPerformed
        // TODO add your handling code here:
        availablepanel.setVisible(false);
        availablebtn.setBackground(Color.white);
        appliedbtn.setBackground(Color.BLUE);
        availablebtn.setEnabled(true);
        appliedpanel.setVisible(true);
        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select * from opportunities inner join "
                    + "apply on opportunities.code=apply.vid and apply.email=?");
            st.setString(1, aouserEmail);
            ResultSet rs=st.executeQuery();
            
            PreparedStatement st1=(PreparedStatement)
            conn.prepareStatement("select * from opportunities inner join "
                    + "apply on opportunities.code=apply.vid and apply.email=?");
            st1.setString(1, aouserEmail);
            ResultSet rs1=st1.executeQuery();
//            String rowCount = Integer.toString(rs1.getRow() );
            
            PreparedStatement st2=(PreparedStatement)
            conn.prepareStatement("select * from opportunities inner join "
                    + "apply on opportunities.code=apply.vid and apply.idtype='APPLIED'");
            ResultSet rs2=st2.executeQuery();
            
//            String rowCount1 = Integer.toString(rs2.getRow());
            
            if(rs1.next()==false)
            {
                appliedbtn.setEnabled(false);
                availablebtn.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Haven't Applied Yet! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while(rs.next())
            {
                String vid=rs.getString("code");
                String title=rs.getString("title");
                String stduentsrequired=rs.getString("studentrequired");
                String applied=rs.getString("studentsapplied");
                String selected=rs.getString("studentsentered");
                

                String tableData[]={vid,title, stduentsrequired, applied, selected};
                DefaultTableModel tableModel=(DefaultTableModel) appliedtable.getModel();
                tableModel.addRow(tableData);
                availablebtn.setEnabled(true);
                
                appliedbtn.setEnabled(false);
            }

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
        }
        DefaultTableModel tableModel=(DefaultTableModel) availabletable.getModel();
        tableModel.setRowCount(0);
        
    }//GEN-LAST:event_appliedbtnActionPerformed

    private void availabletableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_availabletableComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_availabletableComponentShown

    private void appliedtableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_appliedtableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_appliedtableComponentShown

    private void availabletableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availabletableMouseClicked
        // TODO add your handling code here:
        
        
        int row=availabletable.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) availabletable.getModel();
        String vid=model.getValueAt(row, 0).toString();
        ApplyOpportunities ao=new ApplyOpportunities();
        ao.vid=vid;
        ao.aouserEmail=aouserEmail;
        ao.setVisible(true);
        dispose();
    }//GEN-LAST:event_availabletableMouseClicked

    private void statuscrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statuscrossActionPerformed
        // TODO add your handling code here:
        status.setVisible(false);
        statuscross.setVisible(false);
        statusLabel.setVisible(false);
    }//GEN-LAST:event_statuscrossActionPerformed

    private void appliedtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appliedtableMouseClicked
        // TODO add your handling code here:
        
        int row=appliedtable.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) appliedtable.getModel();
        String vid=model.getValueAt(row, 0).toString();
        status.setVisible(true);
        statuscross.setVisible(true);
        statusLabel.setVisible(true);
        String stat="";
        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select idtype from apply where vid=? and email=?");
            st.setString(1,vid);
            st.setString(2, aouserEmail);
            ResultSet rs=st.executeQuery();
            while(rs.next())
                stat=rs.getString("idtype"); 
//            if(stat.equals("APPLIED"))
//                stat="PENDING";
//            
        
        }
        catch(SQLException sqle)
        {
        }
        if(stat.equals("APPLIED"))
            stat="PENDING";        
        statusLabel.setText("Your Status is:"+stat);

        
    }//GEN-LAST:event_appliedtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationApply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appliedbtn;
    private javax.swing.JScrollPane appliedpanel;
    private javax.swing.JTable appliedtable;
    private javax.swing.JButton availablebtn;
    private javax.swing.JScrollPane availablepanel;
    private javax.swing.JTable availabletable;
    private javax.swing.JLabel clickLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton statuscross;
    // End of variables declaration//GEN-END:variables
}
