/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indrajeet
 */
public class ModifyShift extends javax.swing.JFrame {

    /**
     * Creates new form ModifyShift
     */
    public ModifyShift() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        shiftTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        vidforshift = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        loadShiftbtn = new javax.swing.JButton();
        rejectbtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        newEndtime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newStarttime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newShift = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        volid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shiftTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        shiftTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volunteer Title", "Students Name", "Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shiftTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                shiftTableComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(shiftTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, 340, 350));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Volunteer Id :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, -1, -1));

        vidforshift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vidforshift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vidforshiftMouseEntered(evt);
            }
        });
        vidforshift.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                vidforshiftComponentShown(evt);
            }
        });
        getContentPane().add(vidforshift, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 220, 200, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("VOLUNTEER SHIFT LIST");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, -1, -1));

        loadShiftbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loadShiftbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\20\\26 - Zoom.png")); // NOI18N
        loadShiftbtn.setText("LOAD");
        loadShiftbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadShiftbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loadShiftbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 260, 100, -1));

        rejectbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rejectbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\toggle-off.png")); // NOI18N
        rejectbtn.setText("REJECT");
        rejectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rejectbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 170, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\toggle-on.png")); // NOI18N
        jButton3.setText("APPROVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 170, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("New End Time :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        newEndtime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(newEndtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("New Start Time :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        newStarttime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(newStarttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("New Allocated Shift :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        newShift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(newShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText(" REQUEST LIST : ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\20\\26 - Zoom.png")); // NOI18N
        jButton2.setText("LOAD DATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 140, -1));

        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Vol. Id", "Vol. Title", "Current Shift", "Requested Shift"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setHeaderValue("Volunteer Id");
            table.getColumnModel().getColumn(4).setHeaderValue("Current Shift");
            table.getColumnModel().getColumn(5).setHeaderValue("Requested Shift");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 440, 440));

        volid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volidMouseEntered(evt);
            }
        });
        volid.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                volidComponentShown(evt);
            }
        });
        getContentPane().add(volid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Volunteer Id :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, 360, 510));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 460, 510));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 460, 510));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\48\\05 - Arrow Left.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\admin dahsboard.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RequestProvider rp=new RequestProvider();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select * from opportunities inner join apply on "
                    + "opportunities.code=apply.vid inner join requests on "
                    + "opportunities.code=requests.vid and remarks=' ' and requestfor='Shift Change'");
            
            ResultSet rs=st.executeQuery();
            PreparedStatement st1=(PreparedStatement)
            conn.prepareStatement("select * from opportunities inner join apply on "
                    + "opportunities.code=apply.vid inner join requests on "
                    + "opportunities.code=requests.vid and remarks=' ' and requestfor='Shift Change'");
            ResultSet sr=st1.executeQuery();
           if(sr.next()==false)
            {
                JOptionPane.showMessageDialog(this, "No Requests have been made for now! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while(rs.next())
            {
                String name=rs.getString("name");
                String email=rs.getString("email");
                String vid=rs.getString("vid");
                String vTitle=rs.getString("title");
                String currShift=rs.getString("shift");
                String suggestion=rs.getString("suggestion");
                

                String tableData[]={name, email, vid, vTitle, currShift, suggestion};
                DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
                tableModel.addRow(tableData);

                jButton2.setEnabled(false);
                

            }
            

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
            JOptionPane.showMessageDialog(this, "No Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);
       
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tableComponentShown

    private void volidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volidMouseEntered
        // TODO add your handling code here:
//        try{
//            Connection conn=DBConnection.connectDB();
//            PreparedStatement st=(PreparedStatement)
//            conn.prepareStatement("select name, roll, email from users where email=?");
//            st.setString(1,aouserEmail);
//            //            st.setString(1, usernameData);
//            ResultSet rs=st.executeQuery();
//
//            while(rs.next())
//            {
//                name.setText(rs.getString("name"));
//                email.setText(rs.getString("email"));
//                roll.setText(rs.getString("roll"));
//
//                //                String tableData[]={code, title};
//                //                DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
//                //                tableModel.addRow(tableData);
//                //
//                //                jButton2.setEnabled(false);
//
//            }
//
//        }
//        catch(SQLException sqle)
//        {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
//        }
    }//GEN-LAST:event_volidMouseEntered

    private void volidComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_volidComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_volidComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        String vid=volid.getText();
        String uemail=email.getText();
        String starttime=newStarttime.getText();
        String endtime=newEndtime.getText();
        String shift=newShift.getText();
        if(vid.isEmpty() || uemail.isEmpty() || shift.isEmpty() || endtime.isEmpty() || starttime.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Fill Up All the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            Connection loginConn=DBConnection.connectDB();  
            try{
                    PreparedStatement st=(PreparedStatement)
                            loginConn.prepareStatement("update apply set shift=?, starttime=?, endtime=? where vid=? and email=? ");
                    st.setString(1, shift);
                    st.setString(2,starttime);
                    st.setString(3, endtime);
                    st.setString(4, vid);
                    st.setString(5, uemail);

                    int rs=st.executeUpdate();

                    PreparedStatement st1=(PreparedStatement)
                            loginConn.prepareStatement("update requests set remarks='ACCEPTED' where vid=? and email=? and requestfor='Shift Change'");
                    st1.setString(1, vid);
                    st1.setString(2,uemail);
                    st1.executeUpdate();


                    JOptionPane.showMessageDialog(this, "Request Procesed Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    ModifyShift ms=new ModifyShift();
                    ms.setVisible(true);

                } 
                catch(SQLException se)
                {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "No such Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);

                }
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rejectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectbtnActionPerformed
        // TODO add your handling code here:
        
        String vid=volid.getText();
        String uemail=email.getText();
        if(vid.isEmpty() || uemail.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Fill Up All the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            Connection loginConn=DBConnection.connectDB(); 
            try{

                    PreparedStatement st=(PreparedStatement)
                            loginConn.prepareStatement("update requests set remarks='REJECTED' where vid=? and email=? and requestfor='Shift Change'");
                    st.setString(1, vid);
                    st.setString(2,uemail);
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Request Successfully Processed", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    ModifyShift ms=new ModifyShift();
                    ms.setVisible(true);

                } 
                catch(SQLException se)
                {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, se);
                    JOptionPane.showMessageDialog(this, "No such Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);

                }
        }
        
        
    }//GEN-LAST:event_rejectbtnActionPerformed

    private void loadShiftbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadShiftbtnActionPerformed
        // TODO add your handling code here:
        String vid=vidforshift.getText();
        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select title, shift, name from opportunities inner join apply where apply.vid=?");
            st.setString(1, vid);
            ResultSet rs=st.executeQuery();
            
            if(rs==null)
            {
                JOptionPane.showMessageDialog(this, "No Volunteering Opportunities Available! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while(rs.next())
            {
                String title=rs.getString("title");
                String shift=rs.getString("shift");
                String name=rs.getString("name");
                String tableData[]={title, name, shift};
                DefaultTableModel tableModel=(DefaultTableModel) shiftTable.getModel();
                tableModel.addRow(tableData);
                
                loadShiftbtn.setEnabled(false);

            }

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
        }
        
        
    }//GEN-LAST:event_loadShiftbtnActionPerformed

    private void vidforshiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vidforshiftMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_vidforshiftMouseEntered

    private void vidforshiftComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_vidforshiftComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_vidforshiftComponentShown

    private void shiftTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_shiftTableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftTableComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyShift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyShift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyShift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyShift.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyShift().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadShiftbtn;
    private javax.swing.JTextField newEndtime;
    private javax.swing.JTextField newShift;
    private javax.swing.JTextField newStarttime;
    private javax.swing.JButton rejectbtn;
    private javax.swing.JTable shiftTable;
    private javax.swing.JTable table;
    private javax.swing.JTextField vidforshift;
    private javax.swing.JTextField volid;
    // End of variables declaration//GEN-END:variables
}
