/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indrajeet
 */
public class OptOut extends javax.swing.JFrame {

    /**
     * Creates new form OptOut
     */
    public OptOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        rejectbtn = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        loadbtn = new javax.swing.JButton();
        vid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\toggle-on.png")); // NOI18N
        jButton3.setText("APPROVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 170, 30));

        rejectbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rejectbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\toggle-off.png")); // NOI18N
        rejectbtn.setText("REJECT");
        rejectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectbtnActionPerformed(evt);
            }
        });
        getContentPane().add(rejectbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 150, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 330, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Email Id of the user to be removed :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Vol. Id", "Vol. Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 600, 330));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText(" REQUEST LIST : ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\20\\26 - Zoom.png")); // NOI18N
        jButton2.setText("LOAD REQUESTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 170, -1));

        loadbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loadbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\20\\26 - Zoom.png")); // NOI18N
        loadbtn.setText("LOAD DATA");
        loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loadbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 140, 30));

        vid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 330, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Volunteer Id: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        vCount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vCount.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(vCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 690, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 1050, 570));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\48\\05 - Arrow Left.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\admin dahsboard.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RequestProvider rp=new RequestProvider();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbtnActionPerformed
        // TODO add your handling code here:
        String volid=vid.getText();
        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select count(*) from apply where idtype='ACCEPTED' and vid=?");
                        st.setString(1, volid);
            ResultSet rs=st.executeQuery();
            rs.next();
            int count=rs.getInt(1);
            vCount.setText("You have "+count+" volunteer(s) for the volunteer id: "+volid);
            

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
        }
    }//GEN-LAST:event_loadbtnActionPerformed

    private void tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tableComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String volid=vid.getText();
        String uemail=email.getText();
        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("Select name, email, code, title from opportunities inner join"
                    + " requests where requestfor='Opt Out' and remarks=' '");
            ResultSet rs=st.executeQuery();
            PreparedStatement st1=(PreparedStatement)
            conn.prepareStatement("Select name, email, code, title from opportunities inner join"
                    + " requests where requestfor='Opt Out' and remarks=' '");
            ResultSet sr=st1.executeQuery();

            if(sr.next()==false)
            {
                JOptionPane.showMessageDialog(this, "No Requests have been made for now! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while (rs.next()) 
            {
                String name = rs.getString("name");
                String iemail = rs.getString("email");
                String vId = rs.getString("code");
                String vTitle = rs.getString("title");

                String tableData[] = {name, iemail, vId, vTitle};
                DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
                tableModel.addRow(tableData);

                jButton2.setEnabled(false);

            }
            

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
            JOptionPane.showMessageDialog(this, "Enter Valid Email Id", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String volid=vid.getText();
        String uemail=email.getText();
        if(volid.isEmpty() || uemail.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Fill Up All the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            Connection loginConn=DBConnection.connectDB();
            try{
                PreparedStatement st=(PreparedStatement)
                loginConn.prepareStatement("update apply set idtype='OPT-OUT' where vid=? and email=? ");

                st.setString(1, volid);
                st.setString(2, uemail);

                int rs=st.executeUpdate();

                PreparedStatement st1=(PreparedStatement)
                loginConn.prepareStatement("update requests set remarks='ACCEPTED' where vid=? and email=? and requestfor='Opt Out'");
                st1.setString(1, volid);
                st1.setString(2,uemail);
                st1.execute();

                JOptionPane.showMessageDialog(this, "Request Procesed Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                OptOut ms=new OptOut();
                ms.setVisible(true);

            }
            catch(SQLException se)
            {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, se);
                JOptionPane.showMessageDialog(this, "No such Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void rejectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectbtnActionPerformed
        // TODO add your handling code here:

        String volid=vid.getText();
        String uemail=email.getText();
        if(volid.isEmpty() || uemail.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please Fill Up All the Details", "Error", JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            Connection loginConn=DBConnection.connectDB();
            try{

                PreparedStatement st=(PreparedStatement)
                loginConn.prepareStatement("update requests set remarks='REJECTED' where vid=? and email=? and requestfor='Opt Out'");
                st.setString(1, volid);
                st.setString(2,uemail);
                st.executeUpdate();
                JOptionPane.showMessageDialog(this, "Request Successfully Processed", "Success", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                OptOut ms=new OptOut();
                ms.setVisible(true);

            }
            catch(SQLException se)
            {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, se);
                JOptionPane.showMessageDialog(this, "No such Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
        

    }//GEN-LAST:event_rejectbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadbtn;
    private javax.swing.JButton rejectbtn;
    private javax.swing.JTable table;
    private javax.swing.JLabel vCount;
    private javax.swing.JTextField vid;
    // End of variables declaration//GEN-END:variables
}
