/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indrajeet
 */
public class SelectApplicant extends javax.swing.JFrame {

    /**
     * Creates new form SelectApplicant
     */
    String vid1="";
    public SelectApplicant() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vid = new javax.swing.JTextField();
        vidView = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        endtime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        starttime = new javax.swing.JTextField();
        shift = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        reject = new javax.swing.JButton();
        accept = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 380, 30));

        vidView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vidView.setText("Volunteer Id :");
        getContentPane().add(vidView, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Leave the below fields blank in case of candidate rejection");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 490, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Allocated Shift(Day/Noon/Evening)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 240, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Start Time (in hh:mm:ss)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 220, 30));

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volunteer ID", "Volunteering Opportunities", "Applicant Name", "Applicant Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(24);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 510, 410));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("End Time (in hh:mm:ss)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 220, 30));

        endtime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(endtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 240, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("To Accept/Reject the Applicant, Just Click the Respective Rows");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 470, 30));

        starttime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(starttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 240, 40));

        shift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 490, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\20\\26 - Zoom.png")); // NOI18N
        jButton2.setText("LOAD DATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 140, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 490, 40));

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\mobile-interface-icons-2021-10-21-02-36-44-utc\\png\\48\\05 - Arrow Left.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        reject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reject.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\23 - Dislike.png")); // NOI18N
        reject.setText("REJECT");
        reject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectActionPerformed(evt);
            }
        });
        getContentPane().add(reject, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 150, 50));

        accept.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accept.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\user-interface-2022-07-07-00-57-15-utc\\PNG\\24px\\24 - Like.png")); // NOI18N
        accept.setText("ACCEPT");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        getContentPane().add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 170, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\panel transparency new add diagnosis.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 1100, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\indrajeet\\Documents\\NetBeansProjects\\VMS\\VMS ICON\\admin dahsboard.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tableComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageVolunteers mv=new ManageVolunteers();
        mv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
       
        
        String mail=email.getText();
        Connection conn=DBConnection.connectDB();
        try{
            PreparedStatement st=(PreparedStatement) 
                    conn.prepareStatement("update apply set idtype='REJECTED' where email=?");
            st.setString(1, mail);
            st.executeUpdate();
            dispose();
            SelectApplicant sa=new SelectApplicant();
            sa.setVisible(true);
        }
        catch(SQLException sqle)
        {
            JOptionPane.showMessageDialog(this, "Invalid Email", "Error", JOptionPane.ERROR_MESSAGE);

            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, sqle);
        }
        DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
    }//GEN-LAST:event_rejectActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        // TODO add your handling code here:
        String mail=email.getText(), start_time=starttime.getText(), end_time=endtime.getText(), vshift=shift.getText();
        
        Connection conn=DBConnection.connectDB();
        try{
            PreparedStatement st=(PreparedStatement) 
                    conn.prepareStatement("update apply set idtype='ACCEPTED', shift=?, starttime=?, endtime=? where email=? ");
            
            st.setString(1, vshift);
            st.setString(2, start_time);
            st.setString(3, end_time);
            st.setString(4, mail);
            
            st.executeUpdate();
            PreparedStatement st1=(PreparedStatement) 
                    conn.prepareStatement("update opportunities set studentsentered=studentsentered+1 where code=? ");
            st1.setString(1, vid1);
            st1.executeUpdate();
            
            dispose();
            SelectApplicant sa=new SelectApplicant();
            sa.setVisible(true);
        }
        catch(SQLException sqle)
        {
            JOptionPane.showMessageDialog(this, "Invalid", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, sqle);
        }
        DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
        tableModel.setRowCount(0);
        
    }//GEN-LAST:event_acceptActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try{
            Connection conn=DBConnection.connectDB();
            PreparedStatement st=(PreparedStatement)
            conn.prepareStatement("select code, title, name, email from apply inner join opportunities on apply.vid=opportunities.code and opportunities.lastdate >= NOW() AND apply.idtype='APPLIED'");
            //            st.setString(1, usernameData);
            ResultSet rs=st.executeQuery();
            
            PreparedStatement st1=(PreparedStatement)
            conn.prepareStatement("select code, title, name, email from apply inner join opportunities on apply.vid=opportunities.code and opportunities.lastdate >= NOW() AND apply.idtype='APPLIED'");
            //            st.setString(1, usernameData);
            ResultSet rs1=st1.executeQuery();
            if(rs1.next()==false)
            {
                JOptionPane.showMessageDialog(this, "No Applicants Available! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
            }
            while(rs.next())
            {
                String code=rs.getString("code");
                String title=rs.getString("title");
                String name=rs.getString("name");
                String mail=rs.getString("email");

                String tableData[]={code, title, name, mail};
                DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
                tableModel.addRow(tableData);
                
                

            }
            

        }
        catch(SQLException sqle)
        {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
        }
        //
        //        try{
            //            Connection conn=DBConnection.connectDB();
            //            PreparedStatement st=(PreparedStatement)
            //            conn.prepareStatement("select name, code, title, remarks, requestfor from opportunities inner join requests");
            //
            //            ResultSet rs=st.executeQuery();
            //            PreparedStatement st1=(PreparedStatement)
            //            conn.prepareStatement("select name, code, title, remarks, requestfor from opportunities inner join requests where opportunities.code=requests.vid");
            //            ResultSet sr=st1.executeQuery();
            //            if(sr.next()==false)
            //            {
                //                JOptionPane.showMessageDialog(this, "No Requests have been made! ", "Found Nothing", JOptionPane.ERROR_MESSAGE);
                //            }
            //            while(rs.next())
            //            {
                //                String name=rs.getString("name");
                //                String code=rs.getString("code");
                //                String vTitle=rs.getString("title");
                //                String remarks=rs.getString("remarks");
                //                String requestfor=rs.getString("requestfor");
                //
                //                String tableData[]={name, code, vTitle, requestfor, remarks};
                //                DefaultTableModel tableModel=(DefaultTableModel) table.getModel();
                //                tableModel.addRow(tableData);
                //
                //                jButton2.setEnabled(false);
                //
                //            }
            //
            //        }
        //        catch(SQLException sqle)
        //        {
            //            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, sqle);
            //            JOptionPane.showMessageDialog(this, "No Requests have been made!!!", "Error", JOptionPane.ERROR_MESSAGE);
            //
            //        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
        int row=table.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        vid.setText(model.getValueAt(row, 0).toString());
        email.setText(model.getValueAt(row, 3).toString());
        vid1=vid.getText();
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectApplicant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectApplicant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton reject;
    private javax.swing.JTextField shift;
    private javax.swing.JTextField starttime;
    private javax.swing.JTable table;
    private javax.swing.JTextField vid;
    private javax.swing.JLabel vidView;
    // End of variables declaration//GEN-END:variables
}
